# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  prompt cloud
fi

# Aliases
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias gogo='~/Developer/go/src/github.com/twhitacre'
alias proj='~/Projects'
alias term='itermocil'
alias pyserver='python -m SimpleHTTPServer 9000'
alias weather='curl -4 wttr.in/Atlanta'
alias v='nvim .'
alias vim='nvim'
alias yolo='git push origin master && git push heroku master'
alias yolo_production='git push origin master && git push production master'
alias yolo_staging='git push origin staging && git push staging staging:master'
alias dot='~/.dotfiles'
alias nukenm='find . -name "node_modules" -type d -prune -exec rm -rf "{}" +'
alias ngrok='~/Scripts/ngrok'
alias flane='bundle exec fastlane'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"
alias gclean='git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d && git fetch -p'

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# The Rubies
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# The Nodes
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Auto Switching for Node via `nvm use` 
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# Golang Settings
export GOPATH=$HOME/Developer/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# New Story Specfics
alias ns='~/NewStory/code/hit'
alias nsmobile='cd ~/NewStory/code/hit/mobile-impact && yarn xcode && code . && yarn start'

# Yarn Config Path (original/old commentd out)
#export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$PATH:$(yarn global bin)"

# Android Shit
alias pixel='emulator @Pixel_2_API_28'
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Fastlane
export PATH="$HOME/.fastlane/bin:$PATH"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/Tim/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/Tim/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/Tim/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/Tim/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

