#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias iron='~/TIY'
alias gogo='~/Projects/Go/src/github.com/twhitacre'
alias term='itermocil'
alias pyserver='python -m SimpleHTTPServer 9000'
alias weather='curl -4 wttr.in/Atlanta'
alias v='vim .'
alias yolo='git push origin master && git push heroku master'
alias ace='./ace'

alias do_personal='ssh root@104.131.24.10'
alias do_projects='ssh tim@159.203.91.123'
alias do_produce='ssh tim@107.170.89.24'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# The Rubies
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export PATH=/usr/local/sbin:${PATH}

# Golang Settings
export GOPATH=$HOME/Projects/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# export path="$path:$home/.rvm/bin" # add rvm to path for scripting
