#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias e='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias do_personal='ssh root@104.131.24.10'
alias do_projects='ssh tim@159.203.91.123'
alias iron='~/TIY/Cohorts/Cohort-6'
alias gogo='~/Go/src/github.com/twhitacre'
alias term='itermocil'
alias pyserver='python -m SimpleHTTPServer 8000'
alias weather='curl -4 wttr.in/Atlanta'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# GHI Commands
alias assign_issue="sh ~/Shell\ Scripts/tiy-assignment.sh"

# The Rubies
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export PATH=/usr/local/sbin:${PATH}

# Golang Settings
export GOPATH=$HOME/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
