#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias e='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias v='vim'
alias c='clear'
alias do_personal='ssh root@104.131.24.10'
alias do_projects='ssh root@107.170.20.87'
alias iron='~/TIY/Cohorts/Cohort\ 5/'

# Custom Deploy Git Commands
alias gstage="git push staging master"
alias gprod="git push production master"

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# GHI Commands
alias assign_issue="sh ~/Shell\ Scripts/tiy-assignment.sh"

# The Rubies
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
